version: "3"

services:
  db:
    build: .docker/postgres
    container_name: blogapi-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "blogdb"

  pgadmin:
    image: dpage/pgadmin4
    container_name: blogapi-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db

  app:
    container_name: blogapi
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/blogdb?schema=public"
      PORT: "3333"
    command: [ "npx", "prisma", "migrate", "dev" ]
    ports:
      - "3333:3333"
    depends_on:
      - db
